services:
  - type: keyvalue
    name: cellusys-cache
    plan: free
    region: frankfurt
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  - type: web
    name: cellusys-codecamp
    runtime: python
    plan: free
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.9"
      - key: REDIS_URL
        fromService:
          name: cellusys-cache
          type: keyvalue
          property: connectionString
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: SENTRY_DSN
        sync: false
