"""hash password reset tokens

Revision ID: b7e1a2f4c0d9
Revises: 9ab2650e475f
Create Date: 2026-08-03 07:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e1a2f4c0d9'
down_revision = '9ab2650e475f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_reset_token_hash'), ['reset_token_hash'], unique=True)
        batch_op.drop_constraint('uq_users_reset_token', type_='unique')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_users_reset_token', ['reset_token'])
        batch_op.drop_index(batch_op.f('ix_users_reset_token_hash'), table_name='users')
        batch_op.drop_column('reset_token_hash')

    # ### end Alembic commands ###
